### ISSUE TITLE
Questions on "dramatically streamlined"

### ISSUE THREAD

**Issue by DKXXXL** [AndrasKovacs/glue#1]
Dear Kovacs and Kaposi,
    Hello. This issue is about a question in your readme, where it says

> ... as the definition of weak morphism could be dramatically streamlined ...

I want to ask, what do you mean by "dramatically streamlined"? Is there some reference for that?

Also great thanks for all the publication on _gluing_ and _model type theory using QIIT_. They are quite helpful for people without enough category background like me.  

Thanks!
Ende

**Comment by akaposi** [comment]
Thanks for the interest!

You can make the notion of pseudomorphism/weak morphism (in https://drops.dagstuhl.de/opus/volltexte/2019/10532/pdf/LIPIcs-FSCD-2019-25.pdf#page=9 ) shorter by replacing the components for the empty context and context extension. Here are all the components of a weak morphism from S to M (one per line) and what can be made shorter:

F    : S.Con → M.Con
F    : S.Sub Γ ∆ → M.Sub (F Γ) (F ∆)
F.∘  : F (σ S.◦ δ) = F σ M.◦ F δ
F.id : F S.id = M.id

instead of the following two lines you should say that (M.ε : M.Sub (F S.∙) M.∙) has an inverse:

F.∙  : F S.∙ ≅ M.∙
F.ε  : F S.ε = F.∙⁻¹ ∘ M.ε

F    : S.Ty j Γ → M.Ty j (F Γ)
F    : S.Tm Γ A → M.Tm (F Γ) (F A)
F[]  : F (A S.[σ]) = (F A) M.[F σ]
F[]  : F (t S.[σ]) = (F t) M.[F σ]

instead of the following five lines you should say that ((F S.p M., F S.q) : M.Sub (F(Γ S.▹ A)) (F Γ M.▹ F A)) has an inverse:

F.▹  : F (Γ S.▹ A) ≅ F Γ M.▹ F A
F.▹∘ : F.▹ ∘ F (σ∘p,q) = ((F σ)∘p,q) ∘ F.▹
F.,  : F (σ,t) = F.▹⁻¹ ∘ (F σ , F t)
F.p  : F S.p = p ◦ F.▹
F.q  : F S.q = q[F.▹]
